export const galleryImages = [
  'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85',
]

export const pageData = {
  windowFilms: ['Window Films', 'The right shade, performance and protection for your vehicle.', 'Choose a film that suits the way you drive. Tintopia offers standard, ceramic, chameleon and windshield protection options, installed with precision in our Bristol workshop.', 'Film options', ['Standard window film', 'Ceramic window film', 'Chameleon window film', 'Windshield protection film']],
  standardFilms: ['Standard Window Film', 'Clean, understated privacy for every day.', 'Our standard Global film gives your vehicle a refined look while helping reduce UV exposure, glare and interior heat. Available in shades from 5% to 70% VLT.', 'Why choose standard film', ['Factory-style appearance', 'Privacy levels from subtle to limo dark', 'UV and glare reduction', 'A durable, professional finish']],
  ceramicFilms: ['Ceramic Window Film', 'Premium heat rejection without compromise.', 'Ceramic technology improves cabin comfort and optical clarity while avoiding interference with GPS, mobile, Bluetooth, keyless entry and radio signals.', 'Ceramic performance', ['Enhanced solar heat rejection', 'Excellent optical clarity', 'Stable, long-lasting colour', 'Signal-friendly technology']],
  chameleonFilms: ['Chameleon Window Film', 'Make your windscreen stand out.', 'Chameleon film combines premium heat and UV control with an eye-catching colour-shifting appearance. It is an expressive finish for drivers who want something distinctive.', 'Chameleon highlights', ['Colour-shifting finish', 'Heat and UV protection', 'Reduced windscreen glare', 'Premium ceramic-style performance']],
  windshieldFilm: ['Windshield Protection Film', 'Defend the view ahead.', 'A clear protective layer helps reduce the impact of everyday road debris, scratches and glare while supporting more comfortable driving in bright conditions.', 'Protection benefits', ['Helps guard against small chips', 'Scratch-resistant surface', 'UV and glare reduction', 'Helps extend windscreen life']],
  services: ['Tintopia Services', 'Automotive tinting tailored to your car.', 'From an understated privacy tint to high-performance ceramic and chameleon films, every job is carefully prepared and installed for a smooth, lasting finish.', 'Our service promise', ['Consultation on tint shades', 'Professional film installation', 'Vehicle-specific preparation', 'Aftercare guidance']],
  gallery: ['Tintopia Gallery', 'Real cars. Finished with precision.', 'Browse examples of our recent work across hatchbacks, saloons, SUVs and performance vehicles. Each installation is selected around the owner’s preferred shade and finish.', 'Recent work', ['Daily drivers', 'Performance cars', 'Family SUVs', 'Before and after transformations']],
  bookNow: ['Book Your Tinting', 'Tell us about your vehicle.', 'Share your car make, year, preferred dates and tint shade. We’ll confirm the right film and arrange your booking as quickly as possible.', 'What to include', ['Vehicle make and model', 'Year of registration', 'Preferred tint shade', 'Ideal appointment dates']],
  contact: ['Contact Tintopia Bristol', 'See the films before you decide.', 'Visit us for a free, no-obligation consultation. We’ll help you compare shades and choose a solution for privacy, heat reduction, UV protection or a fresh new look.', 'Workshop details', ['Unit 4, Green Tree Farm', 'Roman Road, Emersons Green', 'Pucklechurch, Bristol BS16 7NT', '07392 010907 · tintopiabristol@gmail.com']],
}
